### ISSUE TITLE
API manual detailing each endpoint

### ISSUE THREAD

**Issue by qaznotquaz** [ZDSRepositories/dotwar#9]
for the sake of @ZDSRepositories not going insane and for people who want to make custom clients

Must have endpoint URL, behavior, required input, optional input, and expected output for:
- [x] /
- [x] /games
- [x] /game/[name]/status
- [x] /game/[name]/scan
- [x] /game/[name]/summary
- [x] /game/[name]/agenda
- [x] /game/[name]/add_order
- [x] /game/[name]/delete_order
- [x] /play

**Comment by ZDSRepositories** [comment]
Must have endpoint URL, behavior, required input, optional input, and expected output for:
- [ ] /
- [ ] /games
- [ ] /game/<name>/status
- [ ] /game/<name>/scan
- [ ] /game/<name>/event_log
- [ ] /game/<name>/agenda
- [ ] /game/<name>/add_order
- [ ] /game/<name>/delete_order
- [ ] /parse

**Comment by ZDSRepositories** [comment]
The manual in question is at:

https://github.com/ZDSRepositories/dotwar/blob/master/API_Manual.md

**Comment by ZDSRepositories** [comment]
Closed: last edit partitioned manual into API endpoints and browser routes and finished detailing each one.
